name: "System Administration Issue Report"
description: "Use this template to report system administration issues or requests."
title: "System Administration Issue: [Short description]"
labels: ["system-admin", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### Please fill out the information below to help us address your issue promptly.

  - type: input
    id: issue_summary
    attributes:
      label: "Issue Summary"
      description: "Provide a brief summary of the issue."
      placeholder: "Briefly describe the issue..."

  - type: textarea
    id: issue_details
    attributes:
      label: "Detailed Description"
      description: "Describe the issue in detail. Include any error messages, steps to reproduce, and the expected outcome."
      placeholder: "Provide as much detail as possible..."

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      description: "Select the priority level of this issue."
      options:
        - "Low"
        - "Medium"
        - "High"

  - type: input
    id: affected_system
    attributes:
      label: "Affected System"
      description: "Specify the system or service affected by this issue."
      placeholder: "e.g., Database server, Network, etc."

  - type: checkboxes
    id: issue_type
    attributes:
      label: "Issue Type"
      description: "Select the type of issue."
      options:
        - label: "Service Outage"
        - label: "Performance Degradation"
        - label: "Configuration Issue"
        - label: "Security Concern"
        - label: "Other"

  - type: input
    id: contact_info
    attributes:
      label: "Contact Information"
      description: "Provide your contact details (email or phone) in case we need more information."
      placeholder: "Your email or phone number"

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes"
      description: "Include any additional information or notes."
      placeholder: "Any other details you want to share..."



