name: Notify on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email via Gmail
        uses: dawidd6/action-send-mail@v1.3.0
        with:
          server_address: smtp.gmail.com       
          server_port: 465         
          secure: true
          from: ${{ secrets.FROM_EMAIL }}         
          to: ${{ secrets.TO_EMAIL }}             
          username: ${{ secrets.USERNAME }}             
          password: ${{ secrets.GMAIL_PASSWORD }}      
          subject: 'New Issue Created'
          body: |
            A new issue has been created in the repository.
            Issue Title: ${{ github.event.issue.title }}
            Issue URL: ${{ github.event.issue.html_url }}
